services:
  # wywywebsite_astro-app:
  #   container_name: wywywebsite_astro
  #   working_dir: /apps/astro-app
  #   build:
  #     context: ../
  #     dockerfile: apps/astro-app/Dockerfile
  #     target: runtime
  #   environment:
  #     CLOUDFLARE_API_TOKEN_FILE: /run/secrets/wywywebsite-astro-cloudflare
  #   entrypoint: /entrypoint.sh
  #   secrets:
  #     - wywywebsite-astro-cloudflare
  #   ports:
  #     - 4321:4321
  #   volumes:
  #     - ../apps/astro-app:/apps/astro-app
  #     - astro-node_modules:/apps/astro-app/node_modules

  wywywebsite_sql-receptionist:
    container_name: sql-receptionist
    tty: true
    # image: gcc:latest
    working_dir: /apps/sql-receptionist
    build:
      context: ../
      dockerfile: apps/sql-receptionist/Dockerfile
      # target: builder
    env_file:
      - path: .env
        required: true
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
    secrets:
      - admin
    networks:
      - wywywebsite_cloudflared
    ports:
      - 2523:2523
    depends_on:
      database:
        condition: service_healthy
    command: ./app

  wywywebsite_create_tables:
    container_name: wywywebsite_create_tables
    tty: true
    working_dir: /apps/create_tables
    build:
      context: ../
      dockerfile: apps/create_tables/Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      database:
        condition: service_healthy
    command: python3 create_tables.py

  wywywebsite_cloudflared:
    working_dir: /apps/cloudflared
    build:
      context: ../
      dockerfile: apps/cloudflared/Dockerfile
    container_name: wywywebsite_cloudflared
    environment:
      TZ: America/Toronto
      TUNNEL_TOKEN_FILE: /run/secrets/wywywebsite-cloudflared-cloudflare
    entrypoint: /entrypoint.sh
    restart: unless-stopped
    secrets:
      - wywywebsite-cloudflared-cloudflare
    networks:
      - wywywebsite_cloudflared

  # @TODO secrets for db authentication
  wywywebsite_database:
    container_name: wywywebsite_postgres
    image: postgres
    working_dir: /apps/postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}", "-p", "${POSTGRES_PORT}" ]
      interval: 5m
      timeout: 5s
      start_period: 3s
      retries: 10
    volumes:
      # - postgres-db:/var/lib/postgresql
      - ./../apps/postgres:/var/lib/postgresql
    shm_size: 128mb
    command: -p ${POSTGRES_PORT}

volumes:
  astro-node_modules:

networks:
  wywywebsite_cloudflared:
    name: wywywebsite_cloudflared

secrets:
  wywywebsite-astro-cloudflare:
    file: ./../secrets/astro-cloudflare-token.txt
  wywywebsite-cloudflared-cloudflare:
    file: ./../secrets/cloudflared-cloudflare-token.txt
  admin:
    file: ./../secrets/admin.txt