services:
  wywywebsite_astro-app:
    container_name: wywywebsite_astro
    working_dir: /apps/astro-app
    build:
      context: ../../
      dockerfile: apps/astro-app/Dockerfile
      target: runtime
    environment:
      CLOUDFLARE_API_TOKEN_FILE: /run/secrets/wywywebsite-astro-cloudflare
    entrypoint: /entrypoint.sh
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/website/.env
        required: true
    secrets:
      - wywywebsite-astro-cloudflare
    ports:
      - 4321:4321
    volumes:
      - ../../apps/astro-app:/apps/astro-app
      - astro-node_modules:/apps/astro-app/node_modules
      - ${UNIVERSAL_CONFIG_DIR}/config.yml:/apps/astro-app/config.yml

volumes:
  astro-node_modules:

secrets:
  wywywebsite-astro-cloudflare:
    file: ${SECRETS_DIR}/website/astro-cloudflare-token.txt
